# Generated by Django 6.0.7 on 2026-07-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('CPU', 'Procesador (CPU)'), ('RAM', 'Memoria RAM'), ('GPU', 'Tarjeta Gráfica (GPU)'), ('MOBO', 'Tarjeta Madre'), ('PSU', 'Fuente de Poder'), ('STORAGE', 'Almacenamiento')], max_length=50)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('condition', models.CharField(choices=[('nuevo', 'Nuevo'), ('usado_bueno', 'Usado (Buen Estado)'), ('reparado', 'Reparado / Reacondicionado')], default='nuevo', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Recibido', 'Recibido'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
