# Generated by Django 6.0.7 on 2026-07-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_donation_address_donation_description_donation_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('PC', 'PC Completa'), ('Componente', 'Componente Suelto')], default='Componente', max_length=50),
        ),
        migrations.AlterField(
            model_name='component',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
